name: bexh-trade-executor-aws-ecs CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.7
      - name: Set Up VirtualEnv
        run: |
          pip3 install pipenv
          make install-dev
      - name: Run Tests
        run: |
          make test
